services:
  clawlet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clawlet
    ports:
      - "18790:18790"
    environment:
      # @see https://github.com/mosaxiv/clawlet?tab=readme-ov-file#supported-providers
      # uses your shell ENV OR a `.env`
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      # copies the local config file to the container
      - ./clawlet.config.json:/root/.clawlet/config.json
    entrypoint: ["clawlet", "gateway"]
    stdin_open: true
    tty: true